sudo: required
language: csharp
mono: none
install:
  - msbuild MyTestWPFApp.sln -t:Restore
script:
  - msbuild ".\MyTestPackage\MyTestPackage.wapproj" /p:configuration=Release /p:AppyBundlePlatforms="x86" /p:AppxBundlePlatforms="x86" /p:AppxBundle=Always
